### ISSUE TITLE
Less result data with search-API than on the website

### ISSUE THREAD

**Issue by u-jung** [ArchivesPortalEuropeFoundation/ape-backend#2]
Hello,

As I try to use the /search/ead API I become aware that there will be much more results if I try the search via the web interface. E.g. a search term 'Deutsch-Südwestafrika' gives me some 6012 results from 2 providers with the API instead of the 6130 results from 25 providers shown by a simple web search. Same issue with other search terms. It seems that only Bundesarchiv and Nationaal Archief provide data via the API. 

So how can I get the entire list of results ? Because even if I know the id of a item not provided by the API, I can't get the content of the item using RESTClient.

Greetings

U. Jung

**Comment by smartKaisar** [comment]
Dear U. Jung,
You will get results if an only if the institutions want it to be searchable/accessible via API. There is a function in institution dashboard, named, OPEN DATA ENABLE. If the institute enables this function, you will able to see the results via API. Otherwise not. 

With Thanks,
Kaisar

**Comment by u-jung** [comment]
Hello,

Thanks for the information. Could you provide a list of archives who enable
the open data option?

Regards

U. Jung

Am 12.10.2017 17:36 schrieb "Md. Kaisar Ali" <notifications@github.com>:

Dear U. Jung,
You will get results if an only if the institutions want it to be
searchable/accessible via API. There is a function in institution
dashboard, named, OPEN DATA ENABLE. If the institute enables this function,
you will able to see the results via API. Otherwise not.

With Thanks,
Kaisar

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArchivesPortalEuropeFoundation/ape-backend/issues/2#issuecomment-336175915>,
or mute the thread

**Comment by smartKaisar** [comment]
You can get the information using API. See the API 
 /institute/getInstitutes 

With thanks,
Kaisar
